name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies if you have any (e.g., Pelican, MkDocs)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican  # or any other static site generator

      # Build the website (example for Pelican)
      - name: Build the website
        run: |
          pelican content  # This generates the static site from your content folder
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # The branch where your website will live
          folder: output  # The folder containing the generated website files (e.g., Pelican's output)
